// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Madrasty_API.Entities;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace Madrasty.Entites;

public partial class ApplicationDbContext : IdentityDbContext<ApplicationUser>
{
    public ApplicationDbContext()
    {
    }

    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {

    }
  

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<DepartmentCourse> DepartmentCourses { get; set; }

    public virtual DbSet<Instructor> Instructors { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<StudentCourse> StudentCourses { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasIndex(e => e.TopicId, "IX_Courses_TopicId");

            entity.Property(e => e.Name).IsRequired();

            entity.HasOne(d => d.Topic).WithMany(p => p.Courses).HasForeignKey(d => d.TopicId);

            entity.HasMany(d => d.Departments).WithMany(p => p.Courses)
                .UsingEntity<DepartmentCourse>(
                    r => r.HasOne(d => d.Department).WithMany(p => p.DepartmentCourses).HasForeignKey(d => d.DepartmentId),
                    l => l.HasOne(d => d.Course).WithMany(p => p.DepartmentCourses).HasForeignKey(d => d.CourseId),
                    j =>
                    {
                        j.HasKey(d => new { d.CourseId, d.DepartmentId });
                        j.ToTable("DepartmentCourses");
                        j.HasIndex(d => d.DepartmentId, "IX_DepartmentCourses_DepartmentId");
                    });
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.Property(e => e.Location).IsRequired();
            entity.Property(e => e.Name).IsRequired();
        });

        modelBuilder.Entity<Instructor>(entity =>
        {
            entity.HasIndex(e => e.DepartmentId, "IX_Instructors_DepartmentId");

            entity.Property(e => e.Degree).IsRequired();
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.Salary).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Department).WithMany(p => p.Instructors).HasForeignKey(d => d.DepartmentId);

            entity.HasMany(d => d.Courses).WithMany(p => p.Instructors)
                .UsingEntity<Dictionary<string, object>>(
                    "InstructorCourse",
                    r => r.HasOne<Course>().WithMany().HasForeignKey("CourseId"),
                    l => l.HasOne<Instructor>().WithMany().HasForeignKey("InstructorId"),
                    j =>
                    {
                        j.HasKey("InstructorId", "CourseId");
                        j.ToTable("InstructorCourses");
                        j.HasIndex(new[] { "CourseId" }, "IX_InstructorCourses_CourseId");
                    });
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasIndex(e => e.DepartmentId, "IX_Students_DepartmentId");

            entity.Property(e => e.Address).IsRequired();
            entity.Property(e => e.Name).IsRequired();

            entity.HasOne(d => d.Department).WithMany(p => p.Students).HasForeignKey(d => d.DepartmentId);
        });

        modelBuilder.Entity<StudentCourse>(entity =>
        {
            entity.HasKey(e => new { e.StudentId, e.CourseId });

            entity.HasIndex(e => e.CourseId, "IX_StudentCourses_CourseId");

            entity.HasOne(d => d.Course).WithMany(p => p.StudentCourses).HasForeignKey(d => d.CourseId);

            entity.HasOne(d => d.Student).WithMany(p => p.StudentCourses).HasForeignKey(d => d.StudentId);
        });

        modelBuilder.Entity<Topic>(entity =>
        {
            entity.Property(e => e.Name).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}