// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Madrasty.Entites;

public partial class Student
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public int Age { get; set; }

    public int DepartmentId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new List<StudentCourse>();
}